version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ts_cms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ts_cms
    ports:
      - "3318:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ts_cms_network

volumes:
  mysql_data:
    driver: local

networks:
  ts_cms_network:
    driver: bridge
